### ISSUE TITLE
Login API

### ISSUE THREAD

**Issue by gustavolago** [cgugovbr/comprasgovbr-crawler#4]
Bom dia!

Onde consigo usuário e senha para acesso à API de Compras Governamentais? Já procurei a internet toda por essa informação e não acho. Poderia, por gentiliza, me informar o caminho?

Obrigado!

**Comment by evertramos** [comment]
Olá @gustavolago,

Caso seja vinculado a algum órgão, poderá utilizar seu próprio cpf e senha atualmente cadastrado. Se não tiver um vínculo com um órgão público não sei te dizer. Essa API é para buscar os dados de um órgão específico na API do Compras.

Aqui tem a wiki do Compras:
https://gitlab.com/comprasnet/contratos/-/wikis/home
